schema_version: 1

context:
  version: "0.13.3"

package:
  name: catt
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/c/catt/catt-${{ version }}.tar.gz
  sha256: 012659cddbdb029543dcc7df5d8833f7601d40fd3a8ce53c85f4cd4f1d9b6577

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - catt = catt.cli:main

requirements:
  host:
    - python >=3.7
    - pip
    - poetry
  run:
    - python >=3.7
    - click >=7.1.2
    - ifaddr >=0.1.7
    - pychromecast >=14.0.1,<15
    - requests >=2.23.0
    - yt-dlp >=2023.3.4

tests:
  - python:
      imports:
        - catt
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - script: catt --help

about:
  summary: Cast All The Things allows you to send videos from many, many online sources to your Chromecast.
  license: BSD-2-Clause
  license_file: LICENSE
  homepage: https://github.com/skorokithakis/catt

extra:
  recipe-maintainers:
    - pavelzw
