schema_version: 1

context:
  name: catt
  version: 0.12.12

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/catt-${{ version }}.tar.gz
  sha256: dbb024a1ed37705596db1f957bdeb99123eff26e724082fce23357367c458b73

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - catt = catt.cli:main

requirements:
  host:
    - python >=3.7
    - pip
    - poetry
  run:
    - python >=3.7
    - click >=7.1.2
    - ifaddr >=0.1.7
    - pychromecast >=13.0.7,<14
    - requests >=2.23.0
    - yt-dlp >=2023.3.4

tests:
  - python:
      imports:
        - catt
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
    script:
      - catt --help

about:
  summary: Cast All The Things allows you to send videos from many, many online sources to your Chromecast.
  license: BSD-2-Clause
  license_file: LICENSE
  homepage: https://github.com/skorokithakis/catt

extra:
  recipe-maintainers:
    - pavelzw
